name: Flow-CI-Honkit

on:
  workflow_dispatch:
  push:
    branches:
        - master # pls change trigger on each repos
env:
  USER_EMAIL: ${{secrets.USER_EMAIL}}
  USER_NAME: ${{secrets.USER_NAME}}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  Build-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch snapshot
        run: npm run build
      - name: Build and deploy
        uses: monstar-lab-oss/honkit-ghpages-action@main
