name: Flow-CI-Honkit

on:
  workflow_dispatch:
  push:
    branches:
        - master # pls change trigger on each repos
  schedule:
    - cron: "0 0 * * *"
env:
  USER_EMAIL: ${{secrets.USER_EMAIL}}
  USER_NAME: ${{secrets.USER_NAME}}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  Build-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build and deploy
        uses: iwasthesword/honkit-ghpages-action@main
